# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Pie y Remo
email: eduardo@soijen.com
description: Aventuras a pie y remo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://apieyremo.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
instagram_username: apieyremo
facebook_username: apieyremo
twitter_username: apieyremo
youtube_username: UCHK2qpq7pdjxm8Jab5V4aoQ
#google_analytics_key:
#google_site_verification:
feed: /feed.xml
include: ["_pages"]

#prose.io settings
#prose:
#  rooturl: ''
#  siteurl: ''
#  media: '/assets/images'
#  ignore:
#    - _config.yml
#    - /_layouts
#    - /_includes
#    - .gitignore
#    - robots.txt
#    - sitemap.xml
#    - CNAME
#  metadata:

theme: jekyll-theme-minimal